target_dir = "build"

[dependencies]

miniz = "zip:https://github.com/richgel999/miniz/releases/download/3.1.0/miniz-3.1.0.zip"
tomlc17 = "gh:cktan/tomlc17"
xxHash = "gh:cyan4973/xxHash"

[targets]

dev = {
    build = "clang src/main.c -I.cpk -o cpk",
    ex = "cpk"
}

release = {
    build = "clang src/main.c -O3 -I.cpk -o cpk",
    ex = "cpk"
}