target_dir = "build"

[dependencies]

xxHash = "gh:cyan4973/xxHash"
tomlc17 = "gh:cktan/tomlc17"

[targets]

dev = {
    build = "clang src/main.c -I.cpk -o cpk",
    ex = "cpk"
}

release = {
    build = "clang src/main.c -O3 -I.cpk -o cpk",
    ex = "cpk"
}