target-dir = "build"

[dependencies]
miniz = "zip:https://github.com/richgel999/miniz/releases/download/3.1.0/miniz-3.1.0.zip"
tomlc17 = "git:https://github.com/cktan/tomlc17.git::75565ea37f70c2c9b0013321aede947c10f91d5b"
xxHash = "git:https://github.com/Cyan4973/xxHash.git::c0b5ea995d66691734b1a79ad89e73a0d2fd5a53"

[target.dev]
build = "clang src/main.c -I.cpk -o cpk"
exec = "cpk"

[target.release]
build = "clang src/main.c -O3 -s -I.cpk -o cpk"
exec = "cpk"

[target.release-x86_64]
build = "clang -O3 -s --target=x86_64-linux-gnu src/main.c -I.cpk -o cpk"
exec = "cpk"

[target.release-x86_64-static-musl]
build = "clang -O3 -s --target=x86_64-linux-musl src/main.c -I.cpk -o cpk"
exec = "cpk"

[target.release-aarch64-static-musl]
build = [
    "tar -chf cpk.tar .cpk",
    "docker cp $(docker create $(docker build -f aarch64-static-musl.Dockerfile -q .)):/cpk .",
    "rm cpk.tar",
]