# Dockerfile for building a static binary of cpk using musl libc
# This requires a tarball of the .cpk directory due to docker not copying symlinks.
# run `cpk compile docker-static-musl` to automatically build the executable.

FROM alpine:latest AS build
RUN apk add --no-cache build-base musl-dev

WORKDIR /src

COPY . .
COPY cpk.tar /src/

RUN rm -rf .cpk
RUN tar -xf cpk.tar && rm cpk.tar

RUN gcc -static -O3 -I.cpk src/main.c -o cpk-static-musl

FROM scratch AS export
COPY --from=build /src/cpk-static-musl /
CMD ["cpk-static-musl"]